import type { ExecutiveSnapshot } from "./types";
import { getMetricDefinition } from "./metrics";

export const executiveSnapshotFixture: ExecutiveSnapshot = {
  account: "Northline Growth Group",
  generatedAt: "2026-09-02T18:30:00.000Z",
  state: "simulated",
  release: "V1",
  metrics: [
    {
      id: "attributed_revenue",
      label: getMetricDefinition("attributed_revenue").label,
      value: "$428,640",
      change: "+18.4%",
      direction: "up",
      definition: getMetricDefinition("attributed_revenue").businessDefinition,
    },
    {
      id: "qualified_pipeline",
      label: getMetricDefinition("qualified_pipeline").label,
      value: "$1.24M",
      change: "+9.7%",
      direction: "up",
      definition: getMetricDefinition("qualified_pipeline").businessDefinition,
    },
    {
      id: "speed_to_lead",
      label: getMetricDefinition("speed_to_lead").label,
      value: "23 sec",
      change: "−31 sec",
      direction: "up",
      definition: getMetricDefinition("speed_to_lead").businessDefinition,
    },
    {
      id: "booking_rate",
      label: getMetricDefinition("booking_rate").label,
      value: "38.6%",
      change: "+4.2 pts",
      direction: "up",
      definition: getMetricDefinition("booking_rate").businessDefinition,
    },
  ],
  channels: [
    { name: "Meta", spend: 48200, revenue: 221720, roas: 4.6 },
    { name: "Google", spend: 39100, revenue: 144670, roas: 3.7 },
    { name: "TikTok", spend: 21750, revenue: 58725, roas: 2.7 },
    { name: "Organic", spend: 0, revenue: 35025, roas: 0 },
  ],
  funnel: [
    { label: "Signals", count: 18420, rate: 100 },
    { label: "Leads", count: 2384, rate: 12.9 },
    { label: "Qualified", count: 1198, rate: 50.3 },
    { label: "Appointments", count: 462, rate: 38.6 },
    { label: "Sales", count: 137, rate: 29.7 },
  ],
  alerts: [
    {
      id: "a1",
      severity: "high",
      title: "Voice agent handoff failures increased",
      evidence: "14 failed transfers in 24h; baseline is 3.",
    },
    {
      id: "a2",
      severity: "medium",
      title: "TikTok CAC exceeds guardrail",
      evidence: "$286 CAC versus $240 approved ceiling.",
    },
    {
      id: "a3",
      severity: "medium",
      title: "Attribution conflict needs review",
      evidence: "Meta and Google both claim journey QWA-10482.",
    },
  ],
  recommendation: {
    id: "rec-104",
    title: "Move $4,000 from TikTok prospecting to Meta retargeting",
    expectedImpact: "+$11.2K attributed revenue over 14 days",
    confidence: 82,
    evidence: [
      "Meta retargeting marginal ROAS: 5.1×",
      "TikTok prospecting marginal ROAS: 1.8×",
      "Frequency remains below the 3.5 guardrail",
    ],
    state: "Awaiting Approval",
  },
  journeys: [
    {
      id: "QWA-10482",
      scenario: "success",
      contact: "Elena Torres",
      source: "Meta",
      campaign: "Executive Growth — Q3",
      value: 12400,
      outcome: "Closed won",
      steps: [
        {
          id: "j1",
          label: "Ad clicked",
          system: "Meta Ads",
          occurredAt: "09:14:02",
          status: "completed",
          detail: "Executive Growth creative 04",
          evidence: "fbclid captured",
        },
        {
          id: "j2",
          label: "Lead submitted",
          system: "QWA Forms",
          occurredAt: "09:15:18",
          status: "completed",
          detail: "High-intent assessment form",
          evidence: "Consent and UTM stored",
        },
        {
          id: "j3",
          label: "AI response",
          system: "Quantum Concierge",
          occurredAt: "09:15:37",
          status: "completed",
          detail: "SMS delivered in 19 seconds",
          evidence: "Delivery ID sms_8241",
        },
        {
          id: "j4",
          label: "Qualified",
          system: "Revenue Agent",
          occurredAt: "09:19:44",
          status: "completed",
          detail: "Budget, authority and timing confirmed",
          evidence: "Confidence 91%",
        },
        {
          id: "j5",
          label: "Appointment",
          system: "HighLevel",
          occurredAt: "09:22:06",
          status: "completed",
          detail: "Strategy call booked",
          evidence: "Calendar event ghl_721",
        },
        {
          id: "j6",
          label: "Sales assist",
          system: "QWA Copilot",
          occurredAt: "14:01:10",
          status: "completed",
          detail: "Objection brief shown to rep",
          evidence: "Rep opened brief",
        },
        {
          id: "j7",
          label: "Purchase",
          system: "Stripe",
          occurredAt: "14:38:27",
          status: "completed",
          detail: "$12,400 annual contract",
          evidence: "Payment pi_6382",
        },
        {
          id: "j8",
          label: "Attribution",
          system: "QWA Graph",
          occurredAt: "14:38:31",
          status: "conflict",
          detail: "Meta primary; Google assist disputed",
          evidence: "Review required",
        },
        {
          id: "j9",
          label: "Optimization",
          system: "Decision Agent",
          occurredAt: "14:42:12",
          status: "waiting",
          detail: "Budget shift proposed",
          evidence: "Awaiting human approval",
        },
      ],
    },
    {
      id: "QWA-10483",
      scenario: "abandonment",
      contact: "Marcus Reed",
      source: "Google",
      campaign: "Revenue OS — Search",
      value: 0,
      outcome: "Abandoned",
      steps: [
        {
          id: "a1",
          label: "Lead submitted",
          system: "QWA Forms",
          occurredAt: "10:04:12",
          status: "completed",
          detail: "Demo request captured",
          evidence: "UTM and consent stored",
        },
        {
          id: "a2",
          label: "AI response",
          system: "Quantum Concierge",
          occurredAt: "10:04:31",
          status: "completed",
          detail: "SMS delivered; no reply after three bounded follow-ups",
          evidence: "Journey stopped by contact inactivity rule",
        },
      ],
    },
    {
      id: "QWA-10484",
      scenario: "agent_failure",
      contact: "Priya Shah",
      source: "Meta",
      campaign: "Executive Growth — Q3",
      value: 0,
      outcome: "Agent failed",
      steps: [
        {
          id: "f1",
          label: "Lead submitted",
          system: "QWA Forms",
          occurredAt: "11:17:08",
          status: "completed",
          detail: "High-intent form accepted",
          evidence: "Correlation QWA-10484",
        },
        {
          id: "f2",
          label: "Voice action",
          system: "Quantum Concierge",
          occurredAt: "11:17:29",
          status: "failed",
          detail: "Provider transfer timed out",
          evidence: "Agent run ar_884 · retry queued",
        },
      ],
    },
    {
      id: "QWA-10485",
      scenario: "human_intervention",
      contact: "Daniel Kim",
      source: "TikTok",
      campaign: "Founder Stories",
      value: 7800,
      outcome: "Human assisted",
      steps: [
        {
          id: "h1",
          label: "Qualification paused",
          system: "Revenue Agent",
          occurredAt: "12:08:41",
          status: "waiting",
          detail: "Pricing authority was ambiguous",
          evidence: "Confidence 54% · human review requested",
        },
        {
          id: "h2",
          label: "Human intervention",
          system: "Sales Operations",
          occurredAt: "12:16:03",
          status: "completed",
          detail: "Operator verified authority and resumed workflow",
          evidence: "Audit event ae_411",
        },
      ],
    },
    {
      id: "QWA-10486",
      scenario: "attribution_conflict",
      contact: "Sofia Martins",
      source: "Meta + Google",
      campaign: "Cross-channel retargeting",
      value: 9300,
      outcome: "Conflict",
      steps: [
        {
          id: "c1",
          label: "Purchase",
          system: "Stripe",
          occurredAt: "13:49:22",
          status: "completed",
          detail: "$9,300 contract paid",
          evidence: "Order ord_10486",
        },
        {
          id: "c2",
          label: "Attribution",
          system: "QWA Graph",
          occurredAt: "13:49:25",
          status: "conflict",
          detail: "Meta click and Google branded search both claim primary credit",
          evidence: "Resolution policy requires analyst review",
        },
      ],
    },
    {
      id: "QWA-10487",
      scenario: "approval_pending",
      contact: "Noah Williams",
      source: "Meta",
      campaign: "Executive Growth — Q3",
      value: 15100,
      outcome: "Approval pending",
      steps: [
        {
          id: "p1",
          label: "Revenue attributed",
          system: "QWA Graph",
          occurredAt: "15:03:09",
          status: "completed",
          detail: "$15,100 assigned to Meta retargeting",
          evidence: "Attribution confidence 94%",
        },
        {
          id: "p2",
          label: "Optimization",
          system: "Decision Agent",
          occurredAt: "15:08:54",
          status: "waiting",
          detail: "Daily budget increase proposed within account guardrail",
          evidence: "Recommendation rec_107 awaiting approval",
        },
      ],
    },
  ],
};
