/**
 * Workflow presets and the illustrative cost model behind them.
 *
 * NON-PRODUCTION: every figure here is a simulated relative tier used to
 * compare strategies. Nothing is vendor-quoted or billing-derived.
 */
import type { DurationTarget, ProviderId, UsageRightsStatus } from "./types";

export type RoutingStrategy = "prototype_first" | "premium_everywhere";

export type WorkflowPresetId = "low_cost_prototype" | "commercial_final";

export interface WorkflowStage {
  id: string;
  label: string;
  /** Which layer owns the step — provider-neutral where possible. */
  owner: "planning_provider" | "shot_provider" | "audio_provider" | "code_motion" | "human";
  detail: string;
  /** Rights standing of what this stage produces, before human clearance. */
  producesRights: UsageRightsStatus;
  optional?: boolean;
}

export interface WorkflowPreset {
  id: WorkflowPresetId;
  label: string;
  strategy: RoutingStrategy;
  summary: string;
  /** Publish state this preset can reach without further human action. */
  maxAutomaticState: "ready_for_review" | "ready_for_publish";
  stages: WorkflowStage[];
}

const PLANNING_STAGES: WorkflowStage[] = [
  {
    id: "brief",
    label: "Brief decomposition",
    owner: "human",
    detail: "Objective, audience, offer and duration target become a structured brief.",
    producesRights: "unknown",
  },
  {
    id: "storyboard",
    label: "Storyboard + shot plan",
    owner: "planning_provider",
    detail: "Planning provider returns scenes, shot list, aspect and duration plan.",
    producesRights: "prototype_only",
  },
];

export const WORKFLOW_PRESETS: Record<WorkflowPresetId, WorkflowPreset> = {
  low_cost_prototype: {
    id: "low_cost_prototype",
    label: "Low-cost prototype",
    strategy: "prototype_first",
    summary:
      "Plan and prove the whole spot on the cheapest path. Escalate only the shots that fail the quality bar.",
    maxAutomaticState: "ready_for_review",
    stages: [
      ...PLANNING_STAGES,
      {
        id: "prototype",
        label: "Prototype / rough assembly",
        owner: "planning_provider",
        detail:
          "Low-cost generation and rough cut to test pacing before spending on premium shots.",
        producesRights: "prototype_only",
      },
      {
        id: "voice",
        label: "Voice + audio pass",
        owner: "audio_provider",
        detail: "Scratch or final voice track over the rough cut.",
        producesRights: "unknown",
        optional: true,
      },
      {
        id: "ui_motion",
        label: "UI / product motion",
        owner: "code_motion",
        detail: "Product scenes rendered in code (Motion/GSAP) rather than generated.",
        producesRights: "commercially_cleared",
      },
      {
        id: "escalation",
        label: "Selective premium regeneration",
        owner: "shot_provider",
        detail: "Only shots below the quality threshold are routed to a premium provider.",
        producesRights: "unknown",
      },
      {
        id: "review",
        label: "Rights review",
        owner: "human",
        detail: "Prototype-only material caps the job at review. Publish requires clearance.",
        producesRights: "prototype_only",
      },
    ],
  },
  commercial_final: {
    id: "commercial_final",
    label: "Commercial final",
    strategy: "premium_everywhere",
    summary:
      "Planning may still come from the low-cost hub, but every public-facing asset is generated and cleared on a commercial path.",
    maxAutomaticState: "ready_for_review",
    stages: [
      ...PLANNING_STAGES,
      {
        id: "generation",
        label: "Shot generation",
        owner: "shot_provider",
        detail: "Every delivered shot is generated by a ranked commercial provider.",
        producesRights: "unknown",
      },
      {
        id: "voice",
        label: "Voice + audio",
        owner: "audio_provider",
        detail: "Final voice, music and mix.",
        producesRights: "unknown",
      },
      {
        id: "ui_motion",
        label: "UI / product motion",
        owner: "code_motion",
        detail: "Product scenes rendered in code, owned outright.",
        producesRights: "commercially_cleared",
      },
      {
        id: "clearance",
        label: "Commercial clearance",
        owner: "human",
        detail: "A named reviewer records clearance per asset. Without it the job stays at review.",
        producesRights: "unknown",
      },
    ],
  },
};

export const WORKFLOW_PRESET_IDS = Object.keys(WORKFLOW_PRESETS) as WorkflowPresetId[];

/* ------------------------------------------------------------------ */
/* Illustrative cost comparison                                        */
/* ------------------------------------------------------------------ */

/** Simulated relative unit costs, USD. Not vendor pricing. */
const ILLUSTRATIVE = {
  planningPerSpot: 4,
  prototypePerSecond: 0.06,
  premiumPerSecond: 3.2,
  /** Share of shots that typically need premium regeneration. */
  escalationShare: 0.3,
};

export interface CostComparisonRow {
  durationSeconds: DurationTarget;
  prototypeFirstUsd: number;
  premiumEverywhereUsd: number;
  savingsUsd: number;
  savingsPct: number;
}

export function costComparison(durations: DurationTarget[] = [15, 30, 60]): CostComparisonRow[] {
  return durations.map((durationSeconds) => {
    const premium = durationSeconds * ILLUSTRATIVE.premiumPerSecond;
    const prototype =
      ILLUSTRATIVE.planningPerSpot +
      durationSeconds * ILLUSTRATIVE.prototypePerSecond +
      durationSeconds * ILLUSTRATIVE.escalationShare * ILLUSTRATIVE.premiumPerSecond;
    const round = (n: number) => Math.round(n * 100) / 100;
    return {
      durationSeconds,
      prototypeFirstUsd: round(prototype),
      premiumEverywhereUsd: round(premium),
      savingsUsd: round(premium - prototype),
      savingsPct: Math.round(((premium - prototype) / premium) * 100),
    };
  });
}

export const COST_MODEL_NOTE =
  "Illustrative, non-production figures. Simulated relative tiers for strategy comparison only — not vendor pricing.";

/** Providers referenced by a preset for a given resolved routing decision. */
export function stageOwnerLabel(owner: WorkflowStage["owner"]): string {
  switch (owner) {
    case "planning_provider":
      return "Planning hub";
    case "shot_provider":
      return "Shot provider";
    case "audio_provider":
      return "Voice provider";
    case "code_motion":
      return "Code motion";
    default:
      return "Human";
  }
}

/** Escalation rule: which ranked provider handles a failing prototype shot. */
export function escalationTargets(
  ranked: { providerId: ProviderId; eligible: boolean }[],
): ProviderId[] {
  return ranked.filter((r) => r.eligible).map((r) => r.providerId);
}
