/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IndustriesDentalRouteImport } from './routes/industries/dental'
import { Route as IndustriesHvacRouteImport } from './routes/industries/hvac'
import { Route as IndustriesMedspaRouteImport } from './routes/industries/medspa'
import { Route as IndustriesPlumbingRouteImport } from './routes/industries/plumbing'
import { Route as IndustriesSolarRouteImport } from './routes/industries/solar'
import { Route as InternalAutomationRouteImport } from './routes/internal/automation'
import { Route as InternalControlPlaneRouteImport } from './routes/internal/control-plane'
import { Route as InternalExecutiveRouteImport } from './routes/internal/executive'
import { Route as InternalLeadsRouteImport } from './routes/internal/leads'
import { Route as InternalMediaProductionBriefRouteImport } from './routes/internal/media-production-brief'
import { Route as InternalRevenueRouteImport } from './routes/internal/revenue'
import { Route as InternalVideoRouterLabRouteImport } from './routes/internal/video-router-lab'
import { Route as InternalWorkQueueRouteImport } from './routes/internal/work-queue'
import { Route as ProductsAcquisitionRouteImport } from './routes/products/acquisition'
import { Route as ProductsAttributionRouteImport } from './routes/products/attribution'
import { Route as ProductsBusinessIntelligenceRouteImport } from './routes/products/business-intelligence'
import { Route as ProductsCreativeStudioRouteImport } from './routes/products/creative-studio'
import { Route as ProductsDecisionIntelligenceRouteImport } from './routes/products/decision-intelligence'
import { Route as ProductsLiveCommerceRouteImport } from './routes/products/live-commerce'
import { Route as ProductsRevenueEngineRouteImport } from './routes/products/revenue-engine'
import { Route as ProductsSearchRouteImport } from './routes/products/search'
import { Route as ProductsVoiceRouteImport } from './routes/products/voice'
import { Route as ResourcesWhatIsAnAiRevenueEngineRouteImport } from './routes/resources/what-is-an-ai-revenue-engine'
import { Route as SolutionsAiAppointmentSettingRouteImport } from './routes/solutions/ai-appointment-setting'
import { Route as SolutionsAiLeadResponseRouteImport } from './routes/solutions/ai-lead-response'
import { Route as SolutionsAiVoiceAgentRouteImport } from './routes/solutions/ai-voice-agent'
import { Route as SolutionsCustomerReactivationRouteImport } from './routes/solutions/customer-reactivation'
import { Route as SolutionsRevenueAttributionRouteImport } from './routes/solutions/revenue-attribution'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicLeadsOutboxRouteImport } from './routes/api/public/leads-outbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesDentalRoute = IndustriesDentalRouteImport.update({
  id: '/industries/dental',
  path: '/industries/dental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHvacRoute = IndustriesHvacRouteImport.update({
  id: '/industries/hvac',
  path: '/industries/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesMedspaRoute = IndustriesMedspaRouteImport.update({
  id: '/industries/medspa',
  path: '/industries/medspa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesPlumbingRoute = IndustriesPlumbingRouteImport.update({
  id: '/industries/plumbing',
  path: '/industries/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSolarRoute = IndustriesSolarRouteImport.update({
  id: '/industries/solar',
  path: '/industries/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAutomationRoute = InternalAutomationRouteImport.update({
  id: '/internal/automation',
  path: '/internal/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalControlPlaneRoute = InternalControlPlaneRouteImport.update({
  id: '/internal/control-plane',
  path: '/internal/control-plane',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalExecutiveRoute = InternalExecutiveRouteImport.update({
  id: '/internal/executive',
  path: '/internal/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalLeadsRoute = InternalLeadsRouteImport.update({
  id: '/internal/leads',
  path: '/internal/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalMediaProductionBriefRoute =
  InternalMediaProductionBriefRouteImport.update({
    id: '/internal/media-production-brief',
    path: '/internal/media-production-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalRevenueRoute = InternalRevenueRouteImport.update({
  id: '/internal/revenue',
  path: '/internal/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalVideoRouterLabRoute = InternalVideoRouterLabRouteImport.update({
  id: '/internal/video-router-lab',
  path: '/internal/video-router-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalWorkQueueRoute = InternalWorkQueueRouteImport.update({
  id: '/internal/work-queue',
  path: '/internal/work-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcquisitionRoute = ProductsAcquisitionRouteImport.update({
  id: '/products/acquisition',
  path: '/products/acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAttributionRoute = ProductsAttributionRouteImport.update({
  id: '/products/attribution',
  path: '/products/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBusinessIntelligenceRoute =
  ProductsBusinessIntelligenceRouteImport.update({
    id: '/products/business-intelligence',
    path: '/products/business-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsCreativeStudioRoute = ProductsCreativeStudioRouteImport.update({
  id: '/products/creative-studio',
  path: '/products/creative-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDecisionIntelligenceRoute =
  ProductsDecisionIntelligenceRouteImport.update({
    id: '/products/decision-intelligence',
    path: '/products/decision-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsLiveCommerceRoute = ProductsLiveCommerceRouteImport.update({
  id: '/products/live-commerce',
  path: '/products/live-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRevenueEngineRoute = ProductsRevenueEngineRouteImport.update({
  id: '/products/revenue-engine',
  path: '/products/revenue-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVoiceRoute = ProductsVoiceRouteImport.update({
  id: '/products/voice',
  path: '/products/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesWhatIsAnAiRevenueEngineRoute =
  ResourcesWhatIsAnAiRevenueEngineRouteImport.update({
    id: '/resources/what-is-an-ai-revenue-engine',
    path: '/resources/what-is-an-ai-revenue-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAiAppointmentSettingRoute =
  SolutionsAiAppointmentSettingRouteImport.update({
    id: '/solutions/ai-appointment-setting',
    path: '/solutions/ai-appointment-setting',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAiLeadResponseRoute = SolutionsAiLeadResponseRouteImport.update({
  id: '/solutions/ai-lead-response',
  path: '/solutions/ai-lead-response',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAiVoiceAgentRoute = SolutionsAiVoiceAgentRouteImport.update({
  id: '/solutions/ai-voice-agent',
  path: '/solutions/ai-voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCustomerReactivationRoute =
  SolutionsCustomerReactivationRouteImport.update({
    id: '/solutions/customer-reactivation',
    path: '/solutions/customer-reactivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsRevenueAttributionRoute =
  SolutionsRevenueAttributionRouteImport.update({
    id: '/solutions/revenue-attribution',
    path: '/solutions/revenue-attribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsOutboxRoute = ApiPublicLeadsOutboxRouteImport.update({
  id: '/api/public/leads-outbox',
  path: '/api/public/leads-outbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/medspa': typeof IndustriesMedspaRoute
  '/industries/plumbing': typeof IndustriesPlumbingRoute
  '/industries/solar': typeof IndustriesSolarRoute
  '/internal/automation': typeof InternalAutomationRoute
  '/internal/control-plane': typeof InternalControlPlaneRoute
  '/internal/executive': typeof InternalExecutiveRoute
  '/internal/leads': typeof InternalLeadsRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/revenue': typeof InternalRevenueRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/internal/work-queue': typeof InternalWorkQueueRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/resources/what-is-an-ai-revenue-engine': typeof ResourcesWhatIsAnAiRevenueEngineRoute
  '/solutions/ai-appointment-setting': typeof SolutionsAiAppointmentSettingRoute
  '/solutions/ai-lead-response': typeof SolutionsAiLeadResponseRoute
  '/solutions/ai-voice-agent': typeof SolutionsAiVoiceAgentRoute
  '/solutions/customer-reactivation': typeof SolutionsCustomerReactivationRoute
  '/solutions/revenue-attribution': typeof SolutionsRevenueAttributionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/medspa': typeof IndustriesMedspaRoute
  '/industries/plumbing': typeof IndustriesPlumbingRoute
  '/industries/solar': typeof IndustriesSolarRoute
  '/internal/automation': typeof InternalAutomationRoute
  '/internal/control-plane': typeof InternalControlPlaneRoute
  '/internal/executive': typeof InternalExecutiveRoute
  '/internal/leads': typeof InternalLeadsRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/revenue': typeof InternalRevenueRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/internal/work-queue': typeof InternalWorkQueueRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/resources/what-is-an-ai-revenue-engine': typeof ResourcesWhatIsAnAiRevenueEngineRoute
  '/solutions/ai-appointment-setting': typeof SolutionsAiAppointmentSettingRoute
  '/solutions/ai-lead-response': typeof SolutionsAiLeadResponseRoute
  '/solutions/ai-voice-agent': typeof SolutionsAiVoiceAgentRoute
  '/solutions/customer-reactivation': typeof SolutionsCustomerReactivationRoute
  '/solutions/revenue-attribution': typeof SolutionsRevenueAttributionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/medspa': typeof IndustriesMedspaRoute
  '/industries/plumbing': typeof IndustriesPlumbingRoute
  '/industries/solar': typeof IndustriesSolarRoute
  '/internal/automation': typeof InternalAutomationRoute
  '/internal/control-plane': typeof InternalControlPlaneRoute
  '/internal/executive': typeof InternalExecutiveRoute
  '/internal/leads': typeof InternalLeadsRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/revenue': typeof InternalRevenueRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/internal/work-queue': typeof InternalWorkQueueRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/resources/what-is-an-ai-revenue-engine': typeof ResourcesWhatIsAnAiRevenueEngineRoute
  '/solutions/ai-appointment-setting': typeof SolutionsAiAppointmentSettingRoute
  '/solutions/ai-lead-response': typeof SolutionsAiLeadResponseRoute
  '/solutions/ai-voice-agent': typeof SolutionsAiVoiceAgentRoute
  '/solutions/customer-reactivation': typeof SolutionsCustomerReactivationRoute
  '/solutions/revenue-attribution': typeof SolutionsRevenueAttributionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/dental'
    | '/industries/hvac'
    | '/industries/medspa'
    | '/industries/plumbing'
    | '/industries/solar'
    | '/internal/automation'
    | '/internal/control-plane'
    | '/internal/executive'
    | '/internal/leads'
    | '/internal/media-production-brief'
    | '/internal/revenue'
    | '/internal/video-router-lab'
    | '/internal/work-queue'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/resources/what-is-an-ai-revenue-engine'
    | '/solutions/ai-appointment-setting'
    | '/solutions/ai-lead-response'
    | '/solutions/ai-voice-agent'
    | '/solutions/customer-reactivation'
    | '/solutions/revenue-attribution'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/dental'
    | '/industries/hvac'
    | '/industries/medspa'
    | '/industries/plumbing'
    | '/industries/solar'
    | '/internal/automation'
    | '/internal/control-plane'
    | '/internal/executive'
    | '/internal/leads'
    | '/internal/media-production-brief'
    | '/internal/revenue'
    | '/internal/video-router-lab'
    | '/internal/work-queue'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/resources/what-is-an-ai-revenue-engine'
    | '/solutions/ai-appointment-setting'
    | '/solutions/ai-lead-response'
    | '/solutions/ai-voice-agent'
    | '/solutions/customer-reactivation'
    | '/solutions/revenue-attribution'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/industries/dental'
    | '/industries/hvac'
    | '/industries/medspa'
    | '/industries/plumbing'
    | '/industries/solar'
    | '/internal/automation'
    | '/internal/control-plane'
    | '/internal/executive'
    | '/internal/leads'
    | '/internal/media-production-brief'
    | '/internal/revenue'
    | '/internal/video-router-lab'
    | '/internal/work-queue'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/resources/what-is-an-ai-revenue-engine'
    | '/solutions/ai-appointment-setting'
    | '/solutions/ai-lead-response'
    | '/solutions/ai-voice-agent'
    | '/solutions/customer-reactivation'
    | '/solutions/revenue-attribution'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  IndustriesDentalRoute: typeof IndustriesDentalRoute
  IndustriesHvacRoute: typeof IndustriesHvacRoute
  IndustriesMedspaRoute: typeof IndustriesMedspaRoute
  IndustriesPlumbingRoute: typeof IndustriesPlumbingRoute
  IndustriesSolarRoute: typeof IndustriesSolarRoute
  InternalAutomationRoute: typeof InternalAutomationRoute
  InternalControlPlaneRoute: typeof InternalControlPlaneRoute
  InternalExecutiveRoute: typeof InternalExecutiveRoute
  InternalLeadsRoute: typeof InternalLeadsRoute
  InternalMediaProductionBriefRoute: typeof InternalMediaProductionBriefRoute
  InternalRevenueRoute: typeof InternalRevenueRoute
  InternalVideoRouterLabRoute: typeof InternalVideoRouterLabRoute
  InternalWorkQueueRoute: typeof InternalWorkQueueRoute
  ProductsAcquisitionRoute: typeof ProductsAcquisitionRoute
  ProductsAttributionRoute: typeof ProductsAttributionRoute
  ProductsBusinessIntelligenceRoute: typeof ProductsBusinessIntelligenceRoute
  ProductsCreativeStudioRoute: typeof ProductsCreativeStudioRoute
  ProductsDecisionIntelligenceRoute: typeof ProductsDecisionIntelligenceRoute
  ProductsLiveCommerceRoute: typeof ProductsLiveCommerceRoute
  ProductsRevenueEngineRoute: typeof ProductsRevenueEngineRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
  ProductsVoiceRoute: typeof ProductsVoiceRoute
  ResourcesWhatIsAnAiRevenueEngineRoute: typeof ResourcesWhatIsAnAiRevenueEngineRoute
  SolutionsAiAppointmentSettingRoute: typeof SolutionsAiAppointmentSettingRoute
  SolutionsAiLeadResponseRoute: typeof SolutionsAiLeadResponseRoute
  SolutionsAiVoiceAgentRoute: typeof SolutionsAiVoiceAgentRoute
  SolutionsCustomerReactivationRoute: typeof SolutionsCustomerReactivationRoute
  SolutionsRevenueAttributionRoute: typeof SolutionsRevenueAttributionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLeadsOutboxRoute: typeof ApiPublicLeadsOutboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/dental': {
      id: '/industries/dental'
      path: '/industries/dental'
      fullPath: '/industries/dental'
      preLoaderRoute: typeof IndustriesDentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/hvac': {
      id: '/industries/hvac'
      path: '/industries/hvac'
      fullPath: '/industries/hvac'
      preLoaderRoute: typeof IndustriesHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/medspa': {
      id: '/industries/medspa'
      path: '/industries/medspa'
      fullPath: '/industries/medspa'
      preLoaderRoute: typeof IndustriesMedspaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/plumbing': {
      id: '/industries/plumbing'
      path: '/industries/plumbing'
      fullPath: '/industries/plumbing'
      preLoaderRoute: typeof IndustriesPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/solar': {
      id: '/industries/solar'
      path: '/industries/solar'
      fullPath: '/industries/solar'
      preLoaderRoute: typeof IndustriesSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/automation': {
      id: '/internal/automation'
      path: '/internal/automation'
      fullPath: '/internal/automation'
      preLoaderRoute: typeof InternalAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/control-plane': {
      id: '/internal/control-plane'
      path: '/internal/control-plane'
      fullPath: '/internal/control-plane'
      preLoaderRoute: typeof InternalControlPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/executive': {
      id: '/internal/executive'
      path: '/internal/executive'
      fullPath: '/internal/executive'
      preLoaderRoute: typeof InternalExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/leads': {
      id: '/internal/leads'
      path: '/internal/leads'
      fullPath: '/internal/leads'
      preLoaderRoute: typeof InternalLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/media-production-brief': {
      id: '/internal/media-production-brief'
      path: '/internal/media-production-brief'
      fullPath: '/internal/media-production-brief'
      preLoaderRoute: typeof InternalMediaProductionBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/revenue': {
      id: '/internal/revenue'
      path: '/internal/revenue'
      fullPath: '/internal/revenue'
      preLoaderRoute: typeof InternalRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/video-router-lab': {
      id: '/internal/video-router-lab'
      path: '/internal/video-router-lab'
      fullPath: '/internal/video-router-lab'
      preLoaderRoute: typeof InternalVideoRouterLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/work-queue': {
      id: '/internal/work-queue'
      path: '/internal/work-queue'
      fullPath: '/internal/work-queue'
      preLoaderRoute: typeof InternalWorkQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/acquisition': {
      id: '/products/acquisition'
      path: '/products/acquisition'
      fullPath: '/products/acquisition'
      preLoaderRoute: typeof ProductsAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/attribution': {
      id: '/products/attribution'
      path: '/products/attribution'
      fullPath: '/products/attribution'
      preLoaderRoute: typeof ProductsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/business-intelligence': {
      id: '/products/business-intelligence'
      path: '/products/business-intelligence'
      fullPath: '/products/business-intelligence'
      preLoaderRoute: typeof ProductsBusinessIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/creative-studio': {
      id: '/products/creative-studio'
      path: '/products/creative-studio'
      fullPath: '/products/creative-studio'
      preLoaderRoute: typeof ProductsCreativeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/decision-intelligence': {
      id: '/products/decision-intelligence'
      path: '/products/decision-intelligence'
      fullPath: '/products/decision-intelligence'
      preLoaderRoute: typeof ProductsDecisionIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/live-commerce': {
      id: '/products/live-commerce'
      path: '/products/live-commerce'
      fullPath: '/products/live-commerce'
      preLoaderRoute: typeof ProductsLiveCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/revenue-engine': {
      id: '/products/revenue-engine'
      path: '/products/revenue-engine'
      fullPath: '/products/revenue-engine'
      preLoaderRoute: typeof ProductsRevenueEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/voice': {
      id: '/products/voice'
      path: '/products/voice'
      fullPath: '/products/voice'
      preLoaderRoute: typeof ProductsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/what-is-an-ai-revenue-engine': {
      id: '/resources/what-is-an-ai-revenue-engine'
      path: '/resources/what-is-an-ai-revenue-engine'
      fullPath: '/resources/what-is-an-ai-revenue-engine'
      preLoaderRoute: typeof ResourcesWhatIsAnAiRevenueEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-appointment-setting': {
      id: '/solutions/ai-appointment-setting'
      path: '/solutions/ai-appointment-setting'
      fullPath: '/solutions/ai-appointment-setting'
      preLoaderRoute: typeof SolutionsAiAppointmentSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-lead-response': {
      id: '/solutions/ai-lead-response'
      path: '/solutions/ai-lead-response'
      fullPath: '/solutions/ai-lead-response'
      preLoaderRoute: typeof SolutionsAiLeadResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-voice-agent': {
      id: '/solutions/ai-voice-agent'
      path: '/solutions/ai-voice-agent'
      fullPath: '/solutions/ai-voice-agent'
      preLoaderRoute: typeof SolutionsAiVoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/customer-reactivation': {
      id: '/solutions/customer-reactivation'
      path: '/solutions/customer-reactivation'
      fullPath: '/solutions/customer-reactivation'
      preLoaderRoute: typeof SolutionsCustomerReactivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/revenue-attribution': {
      id: '/solutions/revenue-attribution'
      path: '/solutions/revenue-attribution'
      fullPath: '/solutions/revenue-attribution'
      preLoaderRoute: typeof SolutionsRevenueAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads-outbox': {
      id: '/api/public/leads-outbox'
      path: '/api/public/leads-outbox'
      fullPath: '/api/public/leads-outbox'
      preLoaderRoute: typeof ApiPublicLeadsOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  IndustriesDentalRoute: IndustriesDentalRoute,
  IndustriesHvacRoute: IndustriesHvacRoute,
  IndustriesMedspaRoute: IndustriesMedspaRoute,
  IndustriesPlumbingRoute: IndustriesPlumbingRoute,
  IndustriesSolarRoute: IndustriesSolarRoute,
  InternalAutomationRoute: InternalAutomationRoute,
  InternalControlPlaneRoute: InternalControlPlaneRoute,
  InternalExecutiveRoute: InternalExecutiveRoute,
  InternalLeadsRoute: InternalLeadsRoute,
  InternalMediaProductionBriefRoute: InternalMediaProductionBriefRoute,
  InternalRevenueRoute: InternalRevenueRoute,
  InternalVideoRouterLabRoute: InternalVideoRouterLabRoute,
  InternalWorkQueueRoute: InternalWorkQueueRoute,
  ProductsAcquisitionRoute: ProductsAcquisitionRoute,
  ProductsAttributionRoute: ProductsAttributionRoute,
  ProductsBusinessIntelligenceRoute: ProductsBusinessIntelligenceRoute,
  ProductsCreativeStudioRoute: ProductsCreativeStudioRoute,
  ProductsDecisionIntelligenceRoute: ProductsDecisionIntelligenceRoute,
  ProductsLiveCommerceRoute: ProductsLiveCommerceRoute,
  ProductsRevenueEngineRoute: ProductsRevenueEngineRoute,
  ProductsSearchRoute: ProductsSearchRoute,
  ProductsVoiceRoute: ProductsVoiceRoute,
  ResourcesWhatIsAnAiRevenueEngineRoute: ResourcesWhatIsAnAiRevenueEngineRoute,
  SolutionsAiAppointmentSettingRoute: SolutionsAiAppointmentSettingRoute,
  SolutionsAiLeadResponseRoute: SolutionsAiLeadResponseRoute,
  SolutionsAiVoiceAgentRoute: SolutionsAiVoiceAgentRoute,
  SolutionsCustomerReactivationRoute: SolutionsCustomerReactivationRoute,
  SolutionsRevenueAttributionRoute: SolutionsRevenueAttributionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLeadsOutboxRoute: ApiPublicLeadsOutboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
