/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InternalMediaProductionBriefRouteImport } from './routes/internal/media-production-brief'
import { Route as InternalVideoRouterLabRouteImport } from './routes/internal/video-router-lab'
import { Route as ProductsAcquisitionRouteImport } from './routes/products/acquisition'
import { Route as ProductsAttributionRouteImport } from './routes/products/attribution'
import { Route as ProductsBusinessIntelligenceRouteImport } from './routes/products/business-intelligence'
import { Route as ProductsCreativeStudioRouteImport } from './routes/products/creative-studio'
import { Route as ProductsDecisionIntelligenceRouteImport } from './routes/products/decision-intelligence'
import { Route as ProductsLiveCommerceRouteImport } from './routes/products/live-commerce'
import { Route as ProductsRevenueEngineRouteImport } from './routes/products/revenue-engine'
import { Route as ProductsSearchRouteImport } from './routes/products/search'
import { Route as ProductsVoiceRouteImport } from './routes/products/voice'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicLeadsOutboxRouteImport } from './routes/api/public/leads-outbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalMediaProductionBriefRoute =
  InternalMediaProductionBriefRouteImport.update({
    id: '/internal/media-production-brief',
    path: '/internal/media-production-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalVideoRouterLabRoute = InternalVideoRouterLabRouteImport.update({
  id: '/internal/video-router-lab',
  path: '/internal/video-router-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcquisitionRoute = ProductsAcquisitionRouteImport.update({
  id: '/products/acquisition',
  path: '/products/acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAttributionRoute = ProductsAttributionRouteImport.update({
  id: '/products/attribution',
  path: '/products/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBusinessIntelligenceRoute =
  ProductsBusinessIntelligenceRouteImport.update({
    id: '/products/business-intelligence',
    path: '/products/business-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsCreativeStudioRoute = ProductsCreativeStudioRouteImport.update({
  id: '/products/creative-studio',
  path: '/products/creative-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDecisionIntelligenceRoute =
  ProductsDecisionIntelligenceRouteImport.update({
    id: '/products/decision-intelligence',
    path: '/products/decision-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsLiveCommerceRoute = ProductsLiveCommerceRouteImport.update({
  id: '/products/live-commerce',
  path: '/products/live-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRevenueEngineRoute = ProductsRevenueEngineRouteImport.update({
  id: '/products/revenue-engine',
  path: '/products/revenue-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVoiceRoute = ProductsVoiceRouteImport.update({
  id: '/products/voice',
  path: '/products/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsOutboxRoute = ApiPublicLeadsOutboxRouteImport.update({
  id: '/api/public/leads-outbox',
  path: '/api/public/leads-outbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/media-production-brief': typeof InternalMediaProductionBriefRoute
  '/internal/video-router-lab': typeof InternalVideoRouterLabRoute
  '/products/acquisition': typeof ProductsAcquisitionRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/business-intelligence': typeof ProductsBusinessIntelligenceRoute
  '/products/creative-studio': typeof ProductsCreativeStudioRoute
  '/products/decision-intelligence': typeof ProductsDecisionIntelligenceRoute
  '/products/live-commerce': typeof ProductsLiveCommerceRoute
  '/products/revenue-engine': typeof ProductsRevenueEngineRoute
  '/products/search': typeof ProductsSearchRoute
  '/products/voice': typeof ProductsVoiceRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/leads-outbox': typeof ApiPublicLeadsOutboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/internal/media-production-brief'
    | '/internal/video-router-lab'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/internal/media-production-brief'
    | '/internal/video-router-lab'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/internal/media-production-brief'
    | '/internal/video-router-lab'
    | '/products/acquisition'
    | '/products/attribution'
    | '/products/business-intelligence'
    | '/products/creative-studio'
    | '/products/decision-intelligence'
    | '/products/live-commerce'
    | '/products/revenue-engine'
    | '/products/search'
    | '/products/voice'
    | '/api/public/health'
    | '/api/public/leads-outbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InternalMediaProductionBriefRoute: typeof InternalMediaProductionBriefRoute
  InternalVideoRouterLabRoute: typeof InternalVideoRouterLabRoute
  ProductsAcquisitionRoute: typeof ProductsAcquisitionRoute
  ProductsAttributionRoute: typeof ProductsAttributionRoute
  ProductsBusinessIntelligenceRoute: typeof ProductsBusinessIntelligenceRoute
  ProductsCreativeStudioRoute: typeof ProductsCreativeStudioRoute
  ProductsDecisionIntelligenceRoute: typeof ProductsDecisionIntelligenceRoute
  ProductsLiveCommerceRoute: typeof ProductsLiveCommerceRoute
  ProductsRevenueEngineRoute: typeof ProductsRevenueEngineRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
  ProductsVoiceRoute: typeof ProductsVoiceRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLeadsOutboxRoute: typeof ApiPublicLeadsOutboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/media-production-brief': {
      id: '/internal/media-production-brief'
      path: '/internal/media-production-brief'
      fullPath: '/internal/media-production-brief'
      preLoaderRoute: typeof InternalMediaProductionBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/video-router-lab': {
      id: '/internal/video-router-lab'
      path: '/internal/video-router-lab'
      fullPath: '/internal/video-router-lab'
      preLoaderRoute: typeof InternalVideoRouterLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/acquisition': {
      id: '/products/acquisition'
      path: '/products/acquisition'
      fullPath: '/products/acquisition'
      preLoaderRoute: typeof ProductsAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/attribution': {
      id: '/products/attribution'
      path: '/products/attribution'
      fullPath: '/products/attribution'
      preLoaderRoute: typeof ProductsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/business-intelligence': {
      id: '/products/business-intelligence'
      path: '/products/business-intelligence'
      fullPath: '/products/business-intelligence'
      preLoaderRoute: typeof ProductsBusinessIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/creative-studio': {
      id: '/products/creative-studio'
      path: '/products/creative-studio'
      fullPath: '/products/creative-studio'
      preLoaderRoute: typeof ProductsCreativeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/decision-intelligence': {
      id: '/products/decision-intelligence'
      path: '/products/decision-intelligence'
      fullPath: '/products/decision-intelligence'
      preLoaderRoute: typeof ProductsDecisionIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/live-commerce': {
      id: '/products/live-commerce'
      path: '/products/live-commerce'
      fullPath: '/products/live-commerce'
      preLoaderRoute: typeof ProductsLiveCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/revenue-engine': {
      id: '/products/revenue-engine'
      path: '/products/revenue-engine'
      fullPath: '/products/revenue-engine'
      preLoaderRoute: typeof ProductsRevenueEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/voice': {
      id: '/products/voice'
      path: '/products/voice'
      fullPath: '/products/voice'
      preLoaderRoute: typeof ProductsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads-outbox': {
      id: '/api/public/leads-outbox'
      path: '/api/public/leads-outbox'
      fullPath: '/api/public/leads-outbox'
      preLoaderRoute: typeof ApiPublicLeadsOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InternalMediaProductionBriefRoute: InternalMediaProductionBriefRoute,
  InternalVideoRouterLabRoute: InternalVideoRouterLabRoute,
  ProductsAcquisitionRoute: ProductsAcquisitionRoute,
  ProductsAttributionRoute: ProductsAttributionRoute,
  ProductsBusinessIntelligenceRoute: ProductsBusinessIntelligenceRoute,
  ProductsCreativeStudioRoute: ProductsCreativeStudioRoute,
  ProductsDecisionIntelligenceRoute: ProductsDecisionIntelligenceRoute,
  ProductsLiveCommerceRoute: ProductsLiveCommerceRoute,
  ProductsRevenueEngineRoute: ProductsRevenueEngineRoute,
  ProductsSearchRoute: ProductsSearchRoute,
  ProductsVoiceRoute: ProductsVoiceRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLeadsOutboxRoute: ApiPublicLeadsOutboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
